#pragma once

#include "DataTypeCastModel.h"
#include "DisplayModel.h"
#include "ImageLoaderModel.h"
#include "ImageSaveModel.h"
#include "ImageResizeModel.h"
#include "ImageCropModel.h"
#include "ImageRotateModel.h"
#include "ImageFlipModel.h"
#include "ImageConvertColorModel.h"
#include "ImageBlurModel.h"
#include "ImageGaussianBlurModel.h"
#include "ImageImmedianBlurModel.h"
#include "ImageImbilateralFilter.h"
#include "ImageImthresholeModel.h"
#include "ImageImadaptiveThresh.h"
#include "ImageCannyModel.h"